Repository ContractAssistant/ContractAssistant_FE, pull requests merged in 2023-11, with the labels that each got.

#11 feat: Github Action 배포 관련 내용 추가
  .github/workflow/deploy.yml
  src/main.jsx
  vite.config.js
Labels: Test, Deploy

#14 로그인 폼창 구현하기
  src/App.css
  src/Router.jsx
  src/components/LoginForm.jsx
  src/page/Login.jsx
  src/page/LoginPage.jsx
  src/page/MainPage.jsx
Labels: Feature, Test

#15 feat: 로그인 폼창 구현하기
  src/App.css
  src/Router.jsx
  src/components/LoginForm.jsx
  src/page/Login.jsx
  src/page/LoginPage.jsx
  src/page/MainPage.jsx
Labels: Feature, API, Test

#17 feat: Layout Grid 추가
  src/page/MainPage.jsx
Labels: Feature, Styling

#18 Chat 폼창 구현하기
  .github/workflows/deploy.yml
  src/components/ChatForm.jsx
  src/components/LoginForm.jsx
  src/page/MainPage.jsx
Labels: Feature, API, Test

#19 feat: RightBar top,bottom 칸 추가
  src/page/MainPage.jsx
Labels: Styling

#20 legalTerminology 창 구현(dummy data 추가)
  src/components/LegalTerminology.jsx
Labels: Feature, API, Test

#23 GptAnalytics, ChatForm, Layout 작업 적용
  src/components/ChatForm.jsx
  src/components/GptAnalytics.jsx
  src/components/LegalTerminology.jsx
  src/page/MainPage.jsx
Labels: Feature, Styling, Deploy

#24 ChatListBar 추가
  package-lock.json
  package.json
  src/components/ListBar.jsx
  src/page/MainPage.jsx
  yarn.lock
Labels: Feature, Test

#25 Right Sidebar 관련 내용 작업 진행 완료
  package-lock.json
  package.json
  src/components/ChatForm.jsx
  src/components/GptAnalytics.jsx
  src/components/LegalTerminology.jsx
  src/components/ListBar.jsx
  src/components/Pagination.jsx
  src/page/MainPage.jsx
  yarn.lock
Labels: Refactor, Feature, Styling, Deploy

#26 Develop에서 올린 파일 최종 merge
  src/components/ChatForm.jsx
  src/components/LegalTerminology.jsx
  src/page/MainPage.jsx
Labels: Bug, Refactor, Styling

#27 사이드바 GptAnalaytics 스크롤로 변경 및 스타일 수정
  src/components/ChatForm.jsx
  src/components/GptAnalytics.jsx
Labels: Refactor, Styling

#32 Feat/issue #30
  package-lock.json
  package.json
  src/components/MinWageCal.jsx
  src/page/GptPage.jsx
  yarn.lock
Labels: Feature, Styling

#34 모달창 구현
  package.json
  src/components/BackgroundModal.jsx
  src/components/GptAnalytics.jsx
  src/components/ListBar.jsx
  src/components/MinWageCal.jsx
  src/main.jsx
  src/page/MainPage.jsx
  src/store/useModalStore.js
  yarn.lock
Labels: Feature

#39 채팅방 리스트 별로 구현
  src/components/ListBar.jsx
  src/page/MainPage.jsx
  yarn.lock
Labels: Feature

#41 단어의미 및 표현해석, 유의사항 출력 적용
  src/components/ChatForm.jsx
  src/components/GptAnalytics.jsx
  src/components/LegalTerminology.jsx
  src/components/words.js
Labels: Refactor, API, Styling, Fix

#43 라우터 페이지 연결 수정하기
  .gitignore
  package-lock.json
  package.json
  src/Router.jsx
  src/components/BackgroundModal.jsx
  src/components/ChatForm.jsx
  src/components/GptAnalytics.jsx
  src/components/LegalTerminology.jsx
  src/components/ListBar.jsx
  src/components/LoginForm.jsx
  src/components/MinWageCal.jsx
  src/page/Gpt.jsx
  src/page/GptPage.jsx
  src/page/MainPage.jsx
  src/store/useModalStore.js
  src/store/useStoreGptData.js
  yarn.lock
Labels: Feature

#44 router 맨처음 로그인창 나오고 로그인 버튼 누르면 페이지 넘어가게 설정
  src/Router.jsx
  src/components/LoginForm.jsx
Labels: Feature

#45 Api 관련 내용 적용 및 Chatform 버그 해결
  src/components/ChatForm.jsx
  src/components/GptAnalytics.jsx
  src/components/LegalTerminology.jsx
  src/components/words.js
Labels: Bug, Refactor, API, Fix
